### ISSUE TITLE
How to custom final Redirect URL after authorization in hydra flow ?

### ISSUE THREAD

**Issue by jalr4ever** [dsyer/spring-security-oauth2-hydra#1]
Hi, dsyer:

I have been learned about ORY Hydra work with Spring framework lately, and I performed the whole hydra flow successfully with your demo project.

I found that the project would remember the `BEGIN URL`, and then redirect to this URL after oauth2 flow( authenticate --> authorization).

For Example:

- Input localhost:8080/foo/bar
- Redirect to login page
- Login successfully
- And it finally redirect to `BEGIN URL` (http://localhost:8080/foo/bar)

In the flow, my issues are:

1. How to custom the final redirect url above? 
2. How can I set `access_token` into a cookie for browser after authorization consent? 

I can only find that override the `SavedRequestAwareAuthenticationSuccessHandler#onAuthenticationSuccess()` far from now, but it didn't work at all because it's designed for authentication but not authorization...

Looking forward to your reply, thanks!

**Comment by thinhlai** [comment]
Hi, I'm following this issue. Do you have any solutions ?

**Comment by dsyer** [comment]
1. is just the way Spring Security works. The idea is to authenticate and then go back to the saved request. You can change that behaviour but a) it's nothing to do with this project per se, and b) it's super confusing for users to be redirected to the wrong place.

2. I'm not sure you want an access token in a cookie. The cookie is the session token. That's how it is supposed to work. Again, you could subvert it by changing Spring Security behaviour, but it's not a normally what you want, and it's not what this project was trying to demonstrate.

**Comment by jalr4ever** [comment]
> 1. is just the way Spring Security works. The idea is to authenticate and then go back to the saved request. You can change that behaviour but a) it's nothing to do with this project per se, and b) it's super confusing for users to be redirected to the wrong place.
> 2. I'm not sure you want an access token in a cookie. The cookie is the session token. That's how it is supposed to work. Again, you could subvert it by changing Spring Security behaviour, but it's not a normally what you want, and it's not what this project was trying to demonstrate.

Alright, issues I post are not the point.

**Comment by jalr4ever** [comment]
> Hi, I'm following this issue. Do you have any solutions ?

Debug with the source code, I overriding the **OAuth2AuthorizedClientRepository** for cookie issue and **SavedRequestAwareAuthenticationSuccessHandler** for the callback URL issue, but it's not an elegant and perfect way to do with it I think...
